### ISSUE TITLE
Deprecated Error when running fresh install 

### ISSUE THREAD

**Issue by goigarg** [flightphp/skeleton#3]
This is the error I am getting 

Deprecated

Return type of flight\debug\database\PdoQueryCapture::exec($statement) should either be compatible with PDO::exec(string $statement): int|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

**Comment by n0nag0n** [comment]
What PHP version are you using? That comes if you are using the Tracy Extension and you're on PHP7 but trying to use the PHP8 version or vice versa. You might just need to run `composer require flightphp/tracy-extensions` by hand. I believe 0.1.* is for PHP7 and 0.2.* is for PHP8

**Comment by goigarg** [comment]
I am using php8 and i have updated the tracy-extensions and it worked thanks

**Comment by n0nag0n** [comment]
You're welcome! Tell your friends about Flight! :rocket:
