### ISSUE TITLE
Sql Server Connectivity

### ISSUE THREAD

**Issue by JeffreyAReyes** [flightphp/skeleton#4]
Hi, thank you very much for sharing this lean but very effective framework.

Is it possible to use the framework for a sqlserver database? 

This is how I add in the config.php file:

return [
    'database' => [
        'driver' => 'sqlsrv',
        'host' => 'your_server_name',
        'database' => 'your_database_name',
        'username' => 'your_username',
        'password' => 'your_password',
        'charset' => 'utf8',
        'prefix' => '',
    ],
];

**Comment by n0nag0n** [comment]
Just to make sure I understand you right, you're talking about something like this?

https://stackoverflow.com/questions/18632607/how-to-use-php-to-connect-to-sql-server
